colors:
- [0, 0, 0]
- [127, 213, 114]
- [169, 254, 22]
- [115, 242, 185]
- [221, 36, 235]
- [45, 132, 149]
- [58, 90, 152]
names: [car, person, person_back, bollard, bike, electricscooter, motorcycle]
nc: 7
train: ../168784_2nd_data (with train-val tags)/images/train
val: ../168784_2nd_data (with train-val tags)/images/val
